{
	"schema_version": "1.6.0",
	"id": "CVE-2018-1000808",
	"modified": "2023-11-29T06:24:13.938984Z",
	"published": "2018-10-08T15:29:00Z",
	"aliases": [
		"GHSA-2rcm-phc9-3945",
		"PYSEC-2018-24"
	],
	"related": [
		"USN-3813-1"
	],
	"details": "Python Cryptographic Authority pyopenssl version Before 17.5.0 contains a CWE - 401 : Failure to Release Memory Before Removing Last Reference vulnerability in PKCS #12 Store that can result in Denial of service if memory runs low or is exhausted. This attack appear to be exploitable via Depends upon calling application, however it could be as simple as initiating a TLS connection. Anything that would cause the calling application to reload certificates from a PKCS #12 store.. This vulnerability appears to have been fixed in 17.5.0.",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Alpine:v3.6",
				"name": "py-openssl",
				"purl": "pkg:apk/alpine/py-openssl?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "17.5.0-r0"
						}
					]
				}
			],
			"versions": [
				"0.13-r0",
				"0.14-r0",
				"0.15.1-r0",
				"16.0.0-r0",
				"16.0.0-r1",
				"16.0.0-r2",
				"16.1.0-r0",
				"16.1.0-r1",
				"17.0.0-r1"
			],
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2018-1000808.json"
			}
		},
		{
			"package": {
				"ecosystem": "Alpine:v3.7",
				"name": "py-openssl",
				"purl": "pkg:apk/alpine/py-openssl?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "17.5.0-r0"
						}
					]
				}
			],
			"versions": [
				"0.13-r0",
				"0.14-r0",
				"0.15.1-r0",
				"16.0.0-r0",
				"16.0.0-r1",
				"16.0.0-r2",
				"16.1.0-r0",
				"16.1.0-r1",
				"17.0.0-r1",
				"17.1.0-r1",
				"17.2.0-r1"
			],
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2018-1000808.json"
			}
		},
		{
			"package": {
				"ecosystem": "Alpine:v3.8",
				"name": "py-openssl",
				"purl": "pkg:apk/alpine/py-openssl?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "17.5.0-r0"
						}
					]
				}
			],
			"versions": [
				"0.13-r0",
				"0.14-r0",
				"0.15.1-r0",
				"16.0.0-r0",
				"16.0.0-r1",
				"16.0.0-r2",
				"16.1.0-r0",
				"16.1.0-r1",
				"17.0.0-r1",
				"17.1.0-r1",
				"17.2.0-r1"
			],
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2018-1000808.json"
			}
		},
		{
			"package": {},
			"ranges": [
				{
					"type": "GIT",
					"repo": "https://github.com/pyca/pyopenssl",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "d21fcd810317aa7579af0c194a61af377ade7f0e"
						}
					]
				}
			],
			"versions": [
				"0.14",
				"0.14a2",
				"0.14a3",
				"0.14a4",
				"0.15",
				"0.15.1",
				"16.0.0",
				"16.1.0",
				"16.2.0",
				"17.1.0",
				"17.2.0",
				"17.3.0",
				"17.4.0",
				"v0.14a1"
			],
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2018-1000808.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHSA-2019:0085"
		},
		{
			"type": "WEB",
			"url": "https://github.com/pyca/pyopenssl/pull/723"
		},
		{
			"type": "WEB",
			"url": "http://lists.opensuse.org/opensuse-security-announce/2019-04/msg00014.html"
		},
		{
			"type": "WEB",
			"url": "https://usn.ubuntu.com/3813-1/"
		}
	]
}
