{
	"schema_version": "1.6.0",
	"id": "CVE-2019-19911",
	"modified": "2023-11-08T04:01:29.773452Z",
	"published": "2020-01-05T22:15:11Z",
	"aliases": [
		"GHSA-5gm3-px64-rw72",
		"PYSEC-2020-172"
	],
	"related": [
		"DLA-2057-1",
		"DSA-4631-1",
		"USN-4272-1"
	],
	"details": "There is a DoS vulnerability in Pillow before 6.2.2 caused by FpxImagePlugin.py calling the range function on an unvalidated 32-bit integer if the number of bands is large. On Windows running 32-bit Python, this results in an OverflowError or MemoryError due to the 2 GB limit. However, on Linux running 64-bit Python this results in the process being terminated by the OOM killer.",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Alpine:v3.12",
				"name": "py3-pillow",
				"purl": "pkg:apk/alpine/py3-pillow?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "6.2.2-r0"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2019-19911.json"
			}
		},
		{
			"package": {
				"ecosystem": "Alpine:v3.13",
				"name": "py3-pillow",
				"purl": "pkg:apk/alpine/py3-pillow?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "6.2.2-r0"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2019-19911.json"
			}
		},
		{
			"package": {
				"ecosystem": "Alpine:v3.14",
				"name": "py3-pillow",
				"purl": "pkg:apk/alpine/py3-pillow?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "6.2.2-r0"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2019-19911.json"
			}
		},
		{
			"package": {
				"ecosystem": "Alpine:v3.15",
				"name": "py3-pillow",
				"purl": "pkg:apk/alpine/py3-pillow?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "6.2.2-r0"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2019-19911.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://www.debian.org/security/2020/dsa-4631"
		},
		{
			"type": "WEB",
			"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/3DUMIBUYGJRAVJCTFUWBRLVQKOUTVX5P/"
		},
		{
			"type": "WEB",
			"url": "https://pillow.readthedocs.io/en/stable/releasenotes/6.2.2.html"
		},
		{
			"type": "WEB",
			"url": "https://usn.ubuntu.com/4272-1/"
		},
		{
			"type": "ADVISORY",
			"url": "https://security.alpinelinux.org/vuln/CVE-2019-19911"
		}
	]
}
